version: 0.0
os: linux
files:
  - source: src/ansible
    destination: /etc/ansible

hooks:
  BeforeInstall:
  - location: /deploy.sh
    timeout: 300
    runas: root 
  AfterInstall:
  - location: /deploy.sh
    timeout: 600 
    runas: root
  ApplicationStop:
  - location: /deploy.sh
    timeout: 600
    runas: root
  ApplicationStart:
  - location: /deploy.sh
    timeout: 920
    runas:  root
