# Nginx setup
---
- name: add NGINX yum repo
  yum_repository:
    name: nginx
    description: NGINX YUM repo
    baseurl: http://nginx.org/packages/centos/7/$basearch/
    gpgkey: http://nginx.org/packages/keys/nginx_signing.key
    gpgcheck: yes

- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Deploy Static Nginx config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
  -  { src: "default.conf", dest: "/etc/nginx/conf.d/default.conf" }

- name: Deploy templated Global nginx config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
  - { src: "nginx.conf.j2", dest: "/etc/nginx/nginx.conf" }
  notify: restart_nginx

- name: Deploy vhost config
  template:
    src: nginx-vhost.conf.j2
    dest: /etc/nginx/conf.d/nginx.dbproxy.conf
    owner: root
    group: root
    mode: 0644
  notify: restart_nginx

- name: Start & enable nginx service
  service:
    name: nginx
    state: started
    enabled: yes
